# Generated by Django 2.1.1 on 2019-03-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户姓名')),
                ('pwd', models.CharField(max_length=32, verbose_name='密文密码')),
            ],
            options={
                'verbose_name_plural': 'db_Acount',
                'db_table': 'db_Acount',
            },
        ),
    ]
